# -*- coding: utf-8 -*-
"""CV Assignment- Oil Sketch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOj5KAY69xCfobDOfpgFOy99_Kpzs2Zq
"""

import random
import numpy as np
from matplotlib import pyplot as plt
from skimage import draw
from math import pi

BRUSHES = 50

def process(inputImage):
    brushSize= 5.0
    expressionSize = brushSize * 7.0 #change this value to change level of output clarity
    margin = int(expressionSize * 2)
    halfBrushSize = brushSize // 2

    shape = ((inputImage.shape[0] - 2 * margin)//brushSize, (inputImage.shape[1] - 2 * margin)//brushSize)
    brushes = [draw.ellipse(halfBrushSize, halfBrushSize, brushSize, random.randint(brushSize, expressionSize), rotation=random.random() * pi) for _ in range(BRUSHES)]

    result = np.zeros(inputImage.shape, dtype=np.uint8)

    for x in range(margin, inputImage.shape[0] - margin, int(brushSize)):
        for y in range(margin, inputImage.shape[1] - margin, int(brushSize)):
            ellipseXs, ellipseYs = random.choice(brushes)
            result[x + ellipseXs, y + ellipseYs] = inputImage[x, y]

    return result

'''random.seed(20) #default 0
inputImage = plt.imread("2.jpeg")

flag=1
if inputImage.ndim < 3:
  flag=0
  print('Only RGB or RGBA images supported.')
elif inputImage.ndim == 4:
    inputImage = inputImage[:, :, :3]

if flag==1:
  result= process(inputImage)

from matplotlib import pyplot as plt

# Assuming 'image' is your image array
plt.imshow(result)
plt.axis('off')  # Hide axis
plt.show()'''

"""We're getting a blue-colored image when using cv2_imshow() from google.colab.patches is because cv2_imshow() expects the image to be in BGR format rather than RGB format. OpenCV (which cv2_imshow() uses internally) reads images in BGR format by default.

To display the correct colors, we need to convert the image from RGB to BGR format before passing it to cv2_imshow().
"""

'''import cv2
from google.colab.patches import cv2_imshow

# Convert RGB image to BGR format
result_bgr = cv2.cvtColor(result, cv2.COLOR_RGB2BGR)

# Display the image
cv2_imshow(result_bgr)

from google.colab.patches import cv2_imshow

cv2_imshow(inputImage)

from google.colab.patches import cv2_imshow

cv2_imshow(result)'''