# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7I79tpah03ItOOLKgrbN4zyDV_ncd4A
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def sketch_image(img):

    # Convert the image to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Convert the image to grayscale
    img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # Invert the grayscale image
    img_invert = cv2.bitwise_not(img_gray)

    # Smoothen the inverted image
    img_smoothing = cv2.GaussianBlur(img_invert, (21, 21), sigmaX=0, sigmaY=0)

    # Final sketch image
    final = cv2.divide(img_gray, 255 - img_smoothing, scale=230)

    return final

'''# Example usage
input_image_path = ('/content/sketch.jpeg')
try:
    sketch = sketch_image(input_image_path)

    # Display the sketch image
    plt.figure(figsize=(8,8))
    plt.imshow(sketch, cmap="gray")
    plt.axis("off")
    plt.title("Sketch Image")
    plt.show()
except FileNotFoundError as e:
    print(e)'''

