# -*- coding: utf-8 -*-
"""water_color_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TB67C4DclQD04A9oHz0P11jJsA7LxNSH
"""

import cv2
import matplotlib.pyplot as plt

'''img = cv2.imread('/content/girl.jpg')

plt.axis("off")
watercolour_image = cv2.stylization(img, sigma_s=100, sigma_r=0.45)
plt.imshow(watercolour_image)
cv2.imwrite('watercolour.png', watercolour_image)
plt.show()
'''

def apply_watercolor_effect(img):
    # Apply watercolor effect using OpenCV's stylization function
    watercolour_image = cv2.stylization(img, sigma_s=100, sigma_r=0.45)
    return watercolour_image

    '''# Display the result
    plt.axis("off")
    plt.imshow(watercolour_image)
    plt.show()

    # Save the watercolor-style image
    cv2.imwrite(output_image_path, watercolour_image)'''

'''# Example usage
input_image_path = '/content/girl.jpg'
output_image_path = 'watercolour_output.png'
apply_watercolor_effect(input_image_path, output_image_path)'''